name: Build EXE Tool

on: [push, workflow_dispatch]

jobs:
  build_windows_exe:
    runs-on: windows-latest  # Important: We build on Windows to make a Windows .exe

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          # Install Nuitka along with zstandard (for file compression)
          pip install nuitka zstandard

      - name: Build EXE
        run: |
          python -m nuitka --onefile --assume-yes-for-downloads --company-name="CourseTools" --product-name="CourseExtractor" --file-version="1.0.0.0" -o CourseExtractor.exe course_converter.py

      - name: Upload EXE as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CourseExtractor-Tool
          # Nuitka places the output in the root directory, so we remove the "dist/" folder path
          path: CourseExtractor.exe
